# Generated by Django 4.0.3 on 2022-04-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllNfts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
