# Generated by Django 4.0.3 on 2022-04-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allnfts',
            name='itemid',
            field=models.IntegerField(null=True),
        ),
    ]
