# Generated by Django 4.0.3 on 2022-05-02 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0002_allnfts_itemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='allnfts',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
