# Generated by Django 4.0.3 on 2022-03-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='image',
        ),
        migrations.AddField(
            model_name='banners',
            name='image1',
            field=models.ImageField(null=True, upload_to='media/images/main/banners'),
        ),
        migrations.AddField(
            model_name='banners',
            name='image2',
            field=models.ImageField(null=True, upload_to='media/images/main/banners'),
        ),
        migrations.AddField(
            model_name='banners',
            name='image3',
            field=models.ImageField(null=True, upload_to='media/images/main/banners'),
        ),
    ]
