# Generated by Django 4.0.3 on 2022-03-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_banners_image_banners_image1_banners_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/main'),
        ),
        migrations.AlterField(
            model_name='main_services',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
