# Generated by Django 4.0.3 on 2022-03-09 08:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_main_services_image_alter_main_services_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_services',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
