# Generated by Django 4.0.3 on 2022-03-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_main_services_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_services',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
