# Generated by Django 4.0.3 on 2022-03-09 09:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_main_services_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_services',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='main_services',
            name='image',
            field=models.ImageField(upload_to='media/images/main'),
        ),
        migrations.AlterField(
            model_name='main_services',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
